# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

from waflib import Logs

def build(bld):
    Logs.error("Unit tests are temporary disabled")
    return

    bld(features='cxx',
        target='unit-tests-main',
        name='unit-tests-main',
        source='main.cpp',
        use='BOOST',
        defines=['BOOST_TEST_MODULE=CHRONOSHARE Unit Test'])

    unit_tests = bld.program(
            target='../unit-tests',
            features='cxx cxxprogram',
            source=bld.path.ant_glob(['**/*.cpp'], excl=['main.cpp']),
            use='unit-tests-main',
            install_path=None,
            defines='UNIT_TEST_CONFIG_PATH=\"%s/tmp-files/\"' % (bld.bldnode)
          )
