# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

from waflib import Logs

def build(bld):
    if not bld.env['WITH_TESTS']:
        return

    Logs.error("Most unit tests are temporary disabled")

    bld(features='cxx',
        target='unit-tests-main',
        name='unit-tests-main',
        source='main.cpp',
        use='BOOST',
        includes='.. .',
        defines=['BOOST_TEST_MODULE=ChronoShare Unit Tests'])

    unit_tests = bld.program(
            target='../unit-tests',
            features='cxx cxxprogram',
            source=bld.path.ant_glob(['**/*.cpp'], excl=['main.cpp',
                                                         'unit-tests/**/*.cpp']),
            use='unit-tests-main core-objects chronoshare',
            install_path=None,
            defines='UNIT_TEST_CONFIG_PATH=\"%s/tmp-files/\"' % (bld.bldnode),
            includes='.. ../src .',
          )
